name: recolectores_app_flutter
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.0.0
  geolocator: ^13.0.2
  rive: ^0.8.0
  http: ^0.13.6
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_spinkit: ^5.2.1
  confetti: ^0.8.0

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
    - family: Poppins-Semi
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
    - family: times_new_roman
      fonts:
        - asset: fonts/times_new_roman.ttf
    - family: times_new_roman_bold
      fonts:
        - asset: fonts/times_new_roman_bold.ttf
    - family: times_new_roman_bold_italic
      fonts:
        - asset: fonts/times_new_roman_bold_italic.ttf
    - family: times_new_roman_italic
      fonts:
        - asset: fonts/times_new_roman_italic.ttf

  assets:
    # Add assets from the images directory to the application.
    - images/
    - icons/
